/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * WkFgPanOne.java
 *
 * Created on 04.08.2010, 13:44:05
 */
package de.cismet.cids.custom.objecteditors.wrrl_db_mv;

import Sirius.navigator.connection.SessionManager;
import Sirius.navigator.exception.ConnectionException;

import Sirius.server.middleware.types.MetaClass;
import Sirius.server.middleware.types.MetaObject;

import java.math.BigDecimal;

import java.util.Vector;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;

import de.cismet.cids.custom.util.CidsBeanSupport;

import de.cismet.cids.dynamics.CidsBean;
import de.cismet.cids.dynamics.DisposableCidsBeanStore;

import de.cismet.cids.editors.DefaultCustomObjectEditor;

import de.cismet.cids.navigator.utils.ClassCacheMultiple;

/**
 * DOCUMENT ME!
 *
 * @author   stefan
 * @version  $Revision$, $Date$
 */
public class WkFgPanSix extends javax.swing.JPanel implements DisposableCidsBeanStore {

    //~ Static fields/initializers ---------------------------------------------

    private static final org.apache.log4j.Logger LOG = org.apache.log4j.Logger.getLogger(WkFgPanSix.class);

    //~ Instance fields --------------------------------------------------------

    private final MstTableModel model = new MstTableModel();
    private CidsBean cidsBean;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.cids.editors.DefaultBindableReferenceCombo cbGkPcQk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbVorb;
    private javax.swing.JTable jtMstTab1;
    private javax.swing.JLabel lblGenCond;
    private javax.swing.JLabel lblGenCondBemerkung;
    private javax.swing.JLabel lblGenCondGkQk;
    private javax.swing.JLabel lblGenCondJahr;
    private javax.swing.JLabel lblGenCondMst;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblSpace;
    private javax.swing.JPanel panAllgemein;
    private de.cismet.tools.gui.SemiRoundedPanel panHeadInfo;
    private de.cismet.tools.gui.RoundedPanel panInfo;
    private javax.swing.JPanel panInfoContent;
    private javax.swing.JTextField txtJahrPcqk;
    private javax.swing.JTextField txtMst;
    private javax.swing.JTextField txtPcQkBemerkung;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form WkFgPanOne.
     */
    public WkFgPanSix() {
        initComponents();
        jScrollPane1.getViewport().setOpaque(false);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        panInfo = new de.cismet.tools.gui.RoundedPanel();
        panHeadInfo = new de.cismet.tools.gui.SemiRoundedPanel();
        lblHeading = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panInfoContent = new javax.swing.JPanel();
        lblSpace = new javax.swing.JLabel();
        panAllgemein = new javax.swing.JPanel();
        lblGenCond = new javax.swing.JLabel();
        cbGkPcQk = new de.cismet.cids.editors.DefaultBindableReferenceCombo();
        lblGenCondJahr = new javax.swing.JLabel();
        lblGenCondBemerkung = new javax.swing.JLabel();
        lblGenCondMst = new javax.swing.JLabel();
        txtJahrPcqk = new javax.swing.JTextField();
        txtMst = new javax.swing.JTextField();
        txtPcQkBemerkung = new javax.swing.JTextField();
        lblGenCondGkQk = new javax.swing.JLabel();
        jbVorb = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtMstTab1 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(910, 650));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(910, 650));
        setLayout(new java.awt.BorderLayout());

        panHeadInfo.setBackground(new java.awt.Color(51, 51, 51));
        panHeadInfo.setMinimumSize(new java.awt.Dimension(109, 24));
        panHeadInfo.setPreferredSize(new java.awt.Dimension(109, 24));
        panHeadInfo.setLayout(new java.awt.FlowLayout());

        lblHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblHeading.setText("Allgemeine Physikalisch-Chemische Qualitätskomponenten");
        panHeadInfo.add(lblHeading);

        panInfo.add(panHeadInfo, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        panInfoContent.setMaximumSize(new java.awt.Dimension(777, 400));
        panInfoContent.setMinimumSize(new java.awt.Dimension(777, 400));
        panInfoContent.setOpaque(false);
        panInfoContent.setPreferredSize(new java.awt.Dimension(777, 400));
        panInfoContent.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.weighty = 1.0;
        panInfoContent.add(lblSpace, gridBagConstraints);

        panAllgemein.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panAllgemein.setOpaque(false);
        panAllgemein.setLayout(new java.awt.GridBagLayout());

        lblGenCond.setText(org.openide.util.NbBundle.getMessage(WkFgPanSix.class, "WkFgPanSix.lblGenCond.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panAllgemein.add(lblGenCond, gridBagConstraints);

        cbGkPcQk.setMaximumSize(new java.awt.Dimension(200, 20));
        cbGkPcQk.setMinimumSize(new java.awt.Dimension(200, 20));
        cbGkPcQk.setPreferredSize(new java.awt.Dimension(200, 20));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${cidsBean.gk_pc_qk}"),
                cbGkPcQk,
                org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        cbGkPcQk.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    cbGkPcQkActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panAllgemein.add(cbGkPcQk, gridBagConstraints);

        lblGenCondJahr.setText(org.openide.util.NbBundle.getMessage(
                WkFgPanSix.class,
                "WkFgPanSix.lblGenCondJahr.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panAllgemein.add(lblGenCondJahr, gridBagConstraints);

        lblGenCondBemerkung.setText(org.openide.util.NbBundle.getMessage(
                WkFgPanSix.class,
                "WkFgPanSix.lblGenCondBemerkung.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panAllgemein.add(lblGenCondBemerkung, gridBagConstraints);

        lblGenCondMst.setText(org.openide.util.NbBundle.getMessage(WkFgPanSix.class, "WkFgPanSix.lblGenCondMst.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panAllgemein.add(lblGenCondMst, gridBagConstraints);

        txtJahrPcqk.setMinimumSize(new java.awt.Dimension(100, 20));
        txtJahrPcqk.setPreferredSize(new java.awt.Dimension(100, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${cidsBean.jahr_pcqk}"),
                txtJahrPcqk,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panAllgemein.add(txtJahrPcqk, gridBagConstraints);

        txtMst.setMinimumSize(new java.awt.Dimension(100, 20));
        txtMst.setPreferredSize(new java.awt.Dimension(100, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${cidsBean.mst}"),
                txtMst,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panAllgemein.add(txtMst, gridBagConstraints);

        txtPcQkBemerkung.setMinimumSize(new java.awt.Dimension(200, 20));
        txtPcQkBemerkung.setPreferredSize(new java.awt.Dimension(200, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${cidsBean.pc_qk_bemerkung}"),
                txtPcQkBemerkung,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panAllgemein.add(txtPcQkBemerkung, gridBagConstraints);

        lblGenCondGkQk.setText(org.openide.util.NbBundle.getMessage(
                WkFgPanSix.class,
                "WkFgPanSix.lblGenCondGkQk.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panAllgemein.add(lblGenCondGkQk, gridBagConstraints);

        jbVorb.setText(org.openide.util.NbBundle.getMessage(WkFgPanSix.class, "WkFgPanSix.jbVorb.text")); // NOI18N
        jbVorb.setMinimumSize(new java.awt.Dimension(85, 20));
        jbVorb.setPreferredSize(new java.awt.Dimension(85, 20));
        jbVorb.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    jbVorbActionPerformed(evt);
                }
            });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panAllgemein.add(jbVorb, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 5, 5, 5);
        panInfoContent.add(panAllgemein, gridBagConstraints);

        jScrollPane3.setMinimumSize(new java.awt.Dimension(800, 100));
        jScrollPane3.setOpaque(false);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(800, 100));

        jtMstTab1.setModel(model);
        jScrollPane3.setViewportView(jtMstTab1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 15, 5);
        panInfoContent.add(jScrollPane3, gridBagConstraints);

        jScrollPane1.setViewportView(panInfoContent);

        panInfo.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(panInfo, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void cbGkPcQkActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_cbGkPcQkActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_cbGkPcQkActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void jbVorbActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jbVorbActionPerformed
        final CidsBean measure = getTheCurrentlyWorstMeasure();

        if (measure != null) {
            Object o = measure.getProperty("gk_pc_mst");

            if (o != null) {
                cbGkPcQk.setSelectedItem(o);
            } else {
                cbGkPcQk.setSelectedIndex(-1);
            }

            o = measure.getProperty("messjahr");

            if (o != null) {
                txtJahrPcqk.setText(o.toString());
            } else {
                txtJahrPcqk.setText("");
            }

            o = measure.getProperty("bemerkung_pc");
            if (o != null) {
                txtPcQkBemerkung.setText(o.toString());
            } else {
                txtPcQkBemerkung.setText("");
            }

            o = measure.getProperty("messstelle.messstelle");
            if (o != null) {
                txtMst.setText(o.toString());
            } else {
                txtMst.setText("");
            }
        }
    } //GEN-LAST:event_jbVorbActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    private CidsBean getTheCurrentlyWorstMeasure() {
        final Vector<CidsBean> beans = model.getData();
        int latestYear = 0;
        int worstValue = 0;
        CidsBean measure = null;

        for (final CidsBean cbean : beans) {
            final Integer year = (Integer)cbean.getProperty("messjahr");
            if (year != null) {
                if (latestYear == 0) {
                    latestYear = year;
                    measure = cbean;
                    final CidsBean tmp = (CidsBean)cbean.getProperty("gk_pc_mst");
                    if (cidsBean != null) {
                        try {
                            worstValue = Integer.parseInt((String)tmp.getProperty("value"));
                        } catch (final NumberFormatException e) {
                            LOG.error("Field value does not contain a number", e);
                        }
                    }
                }
            } else {
                if (latestYear == year) {
                    if (cidsBean != null) {
                        try {
                            final CidsBean qualityTmp = (CidsBean)cbean.getProperty("gk_pc_mst");
                            if (qualityTmp != null) {
                                final int valTmp = Integer.parseInt((String)qualityTmp.getProperty("value"));

                                if (valTmp > worstValue) {
                                    worstValue = valTmp;
                                    measure = cbean;
                                }
                            }
                        } catch (final NumberFormatException e) {
                            LOG.error("Field value does not contain a number", e);
                        }
                    }
                } else {
                    break;
                }
            }
        }

        return measure;
    }

    @Override
    public CidsBean getCidsBean() {
        return cidsBean;
    }

    @Override
    public void setCidsBean(final CidsBean cidsBean) {
        bindingGroup.unbind();
        if (cidsBean != null) {
            this.cidsBean = cidsBean;
            DefaultCustomObjectEditor.setMetaClassInformationToMetaClassStoreComponentsInBindingGroup(
                bindingGroup,
                this.cidsBean);
            bindingGroup.bind();
            model.refreshData();
        }
    }

    @Override
    public void dispose() {
        bindingGroup.unbind();
    }

    //~ Inner Classes ----------------------------------------------------------

// @Override
// public void valueChanged(final ListSelectionEvent e) {
// if (!e.getValueIsAdjusting()) {
// if (e.getFirstIndex() > -1) {
// final CidsBean sbean = model.getData().get(e.getFirstIndex());
// Object val = sbean.getProperty("gk_pc_mst");
// if (val != null) {
// lblGkQkVal.setText(val.toString());
// } else {
// lblGkQkVal.setText("");
// }
// val = sbean.getProperty("bemerkung_pc");
// if (val != null) {
// lblBemerkungVal.setText(val.toString());
// } else {
// lblBemerkungVal.setText("");
// }
// val = sbean.getProperty("messjahr");
// if (val != null) {
// lblJahrVal.setText(val.toString());
// } else {
// lblJahrVal.setText("");
// }
// }
// }
// }

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    private class MstTableModel extends AbstractTableModel {

        //~ Instance fields ----------------------------------------------------

        private final MetaClass MC = ClassCacheMultiple.getMetaClass(
                CidsBeanSupport.DOMAIN_NAME,
                "chemie_mst_messungen");
        private String[][] header = {
                { "MST", "messstelle.messstelle" },    // NOI18N
                { "WK", "messstelle.wk_fg.wk_k" },     // NOI18N
                { "Jahr", "messjahr" },                // NOI18N
                { "GK PC MST", "gk_pc_mst" },          // NOI18N
                { "GK GW-Überschreitung?", "" },       // NOI18N
                { "Bemerkung PC Mst", "bemerkung_pc" } // NOI18N
            };
        private Vector<CidsBean> data = new Vector<CidsBean>();

        //~ Methods ------------------------------------------------------------

        @Override
        public int getRowCount() {
            return data.size();
        }

        @Override
        public int getColumnCount() {
            return header.length;
        }

        @Override
        public String getColumnName(final int columnIndex) {
            if (columnIndex < header.length) {
                return header[columnIndex][0];
            } else {
                return "";
            }
        }

        @Override
        public Class<?> getColumnClass(final int columnIndex) {
            return Object.class;
        }

        @Override
        public boolean isCellEditable(final int rowIndex, final int columnIndex) {
            return false;
        }

        @Override
        public Object getValueAt(final int rowIndex, final int columnIndex) {
            if ((rowIndex < data.size()) && (columnIndex < header.length)) {
                if (columnIndex == 4) {
                    // column OW-Überschreitung?
                    return (isLimitExceeded(data.get(rowIndex)) ? "ja" : "nein");
                } else {
                    final Object value = data.get(rowIndex).getProperty(header[columnIndex][1]);
                    if (value != null) {
                        if (value instanceof CidsBean) {
                            return String.valueOf(((CidsBean)value).getProperty("name")); // NOI18N
                        } else {
                            return String.valueOf(value);
                        }
                    } else {
                        return "-";                                                       // NOI18N
                    }
                }
            } else {
                return "";                                                                // NOI18N
            }
        }

        /**
         * DOCUMENT ME!
         *
         * @param   cbean  DOCUMENT ME!
         *
         * @return  DOCUMENT ME!
         */
        private boolean isLimitExceeded(final CidsBean cbean) {
            final String[][] OW = {
                    { "opo4_owert_rakon", "opo4_mittelwert" },
                    { "ges_p_owert_rakon", "ges_p_mittelwert" },
                    { "nh4_owert_rakon", "nh4_mittelwert" },
                    { "no3_n_owert_rakon", "no3_n_mittelwert" },
                    { "ges_n_owert_rakon", "ges_n_mittelwert" },
                    { "cl_owert_rakon", "cl_mittelwert" },
                    { "o2_owert_rakon", "o2_mittelwert" }
                };

            for (int i = 0; i < OW.length; ++i) {
                final BigDecimal ow = (BigDecimal)cbean.getProperty(OW[i][0]);
                final BigDecimal val = (BigDecimal)cbean.getProperty(OW[i][1]);
                if ((ow != null) && (val != null) && (ow.compareTo(val) == -1)) {
                    return true;
                }
            }

            return false;
        }

        @Override
        public void setValueAt(final Object aValue, final int rowIndex, final int columnIndex) {
            // nothing to do, because it is not allowed to modify columns
        }

        /**
         * DOCUMENT ME!
         */
        public void refreshData() {
            try {
                data.clear();
                String query = "select " + MC.getID() + ", m." + MC.getPrimaryKey() + " from " + MC.getTableName(); // NOI18N
                query += " m, chemie_mst_stammdaten s";                                                             // NOI18N
                query += " WHERE m.messstelle = s.id AND s.wk_fg = " + cidsBean.getProperty("id");                  // NOI18N
                query += " order by messjahr desc";                                                                 // NOI18N

                final MetaObject[] MetaObjects = SessionManager.getProxy().getMetaObjectByQuery(query, 0);

                for (final MetaObject mo : MetaObjects) {
                    data.add(mo.getBean());
                }
                fireTableDataChanged();
            } catch (final ConnectionException e) {
                LOG.error("Error while trying to receive measurements.", e); // NOI18N
            }
        }

        /**
         * DOCUMENT ME!
         *
         * @return  DOCUMENT ME!
         */
        public Vector<CidsBean> getData() {
            return data;
        }

        /**
         * DOCUMENT ME!
         */
        public void clearModel() {
            data.clear();
        }
    }
}
