/*
 *  Copyright (C) 2010 stefan
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * WkFgRenderer.java
 *
 * Created on 18.08.2010, 14:31:22
 */

package de.cismet.cids.custom.objectrenderer.wrrl_db_mv;

import de.cismet.cids.custom.util.TabbedPaneUITransparent;
import de.cismet.cids.dynamics.CidsBean;
import de.cismet.cids.tools.metaobjectrenderer.CidsBeanRenderer;
import org.jdesktop.beansbinding.BindingGroup;

/**
 *
 * @author stefan
 */
public class WkKgRenderer extends javax.swing.JPanel implements CidsBeanRenderer {
    private static final org.apache.log4j.Logger LOG = org.apache.log4j.Logger.getLogger(WkGwRenderer.class);

    private CidsBean cidsBean;
    private BindingGroup bindingGroup;

    /** Creates new form WkKgRenderer */
    public WkKgRenderer() {
        bindingGroup = new BindingGroup();
        initComponents();
        tpMain.setUI(new TabbedPaneUITransparent());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tpMain = new javax.swing.JTabbedPane();
        panGeneral = new javax.swing.JPanel();
        wkKgPanOne = new de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanOne();
        panSpacingBottomTab1 = new javax.swing.JPanel();
        panDescriptionAndRisks = new javax.swing.JPanel();
        wkKgPanTwo = new de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanTwo();
        wkKgPanEight = new de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanEight();
        panSpacingBottomTab2 = new javax.swing.JPanel();
        panQualityInformation = new javax.swing.JPanel();
        wkKgPanThree = new de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanThree();
        wkKgPanFour = new de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanFour();
        wkKgPanFive = new de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanFive();
        wkKgPanSix = new de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanSix();
        wkKgPanSeven = new de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanSeven();
        panSpacingBottomTab3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        panGeneral.setOpaque(false);
        panGeneral.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        panGeneral.add(wkKgPanOne, gridBagConstraints);

        panSpacingBottomTab1.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        panGeneral.add(panSpacingBottomTab1, gridBagConstraints);

        tpMain.addTab("Allgemeines", panGeneral);

        panDescriptionAndRisks.setOpaque(false);
        panDescriptionAndRisks.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        panDescriptionAndRisks.add(wkKgPanTwo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        panDescriptionAndRisks.add(wkKgPanEight, gridBagConstraints);

        panSpacingBottomTab2.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        panDescriptionAndRisks.add(panSpacingBottomTab2, gridBagConstraints);

        tpMain.addTab("Beschreibung und Risiken", panDescriptionAndRisks);

        panQualityInformation.setOpaque(false);
        panQualityInformation.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        panQualityInformation.add(wkKgPanThree, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 15);
        panQualityInformation.add(wkKgPanFour, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        panQualityInformation.add(wkKgPanFive, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 0);
        panQualityInformation.add(wkKgPanSix, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        panQualityInformation.add(wkKgPanSeven, gridBagConstraints);

        panSpacingBottomTab3.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        panQualityInformation.add(panSpacingBottomTab3, gridBagConstraints);

        tpMain.addTab("Qualitätsinformationen", panQualityInformation);

        add(tpMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panDescriptionAndRisks;
    private javax.swing.JPanel panGeneral;
    private javax.swing.JPanel panQualityInformation;
    private javax.swing.JPanel panSpacingBottomTab1;
    private javax.swing.JPanel panSpacingBottomTab2;
    private javax.swing.JPanel panSpacingBottomTab3;
    private javax.swing.JTabbedPane tpMain;
    private de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanEight wkKgPanEight;
    private de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanFive wkKgPanFive;
    private de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanFour wkKgPanFour;
    private de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanOne wkKgPanOne;
    private de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanSeven wkKgPanSeven;
    private de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanSix wkKgPanSix;
    private de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanThree wkKgPanThree;
    private de.cismet.cids.custom.objectrenderer.wrrl_db_mv.WkKgPanTwo wkKgPanTwo;
    // End of variables declaration//GEN-END:variables

    @Override
    public CidsBean getCidsBean() {
        return cidsBean;
    }

    @Override
    public void setCidsBean(CidsBean cidsBean) {
        bindingGroup.unbind();
        this.cidsBean = cidsBean;

        if(cidsBean != null) {
            wkKgPanOne.setCidsBean(cidsBean);
            wkKgPanTwo.setCidsBean(cidsBean);
            wkKgPanThree.setCidsBean(cidsBean);
            wkKgPanFour.setCidsBean(cidsBean);
            wkKgPanFive.setCidsBean(cidsBean);
            wkKgPanSix.setCidsBean(cidsBean);
            wkKgPanSeven.setCidsBean(cidsBean);
            wkKgPanEight.setCidsBean(cidsBean);
        }
    }

    @Override
    public void dispose() {
        bindingGroup.unbind();
        wkKgPanOne.dispose();
        wkKgPanTwo.dispose();
        wkKgPanThree.dispose();
        wkKgPanFour.dispose();
        wkKgPanFive.dispose();
        wkKgPanSix.dispose();
        wkKgPanSeven.dispose();
        wkKgPanEight.dispose();
    }

    @Override
    public String getTitle() {
        return org.openide.util.NbBundle.getMessage(WkGwRenderer.class, "WkKgRenderer.title") + String.valueOf(cidsBean);
    }

    @Override
    public void setTitle(String title) {
        //NOP
    }

}
