/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.23 at 11:39:14 AM CET
//
package de.cismet.cids.gaeb.xsd.types;

import java.math.BigDecimal;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Informationen zu einem Artikel.
 *
 * <p>Java class for tgArticle complex type.</p>
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
   &lt;complexType name="tgArticle">
     &lt;complexContent>
       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         &lt;sequence>
           &lt;element name="Brand" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgNormalizedString60" minOccurs="0"/>
           &lt;element name="ArtNo" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgNormalizedString15" minOccurs="0"/>
           &lt;element name="Qty" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgDecimal_11_3" minOccurs="0"/>
           &lt;element name="QU" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgNormalizedString4" minOccurs="0"/>
           &lt;element name="ArtOutline" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgMLText"/>
           &lt;element name="AddText" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgAddText" maxOccurs="unbounded" minOccurs="0"/>
         &lt;/sequence>
       &lt;/restriction>
     &lt;/complexContent>
   &lt;/complexType>
 * </pre>
 *
 * @version  $Revision$, $Date$
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "tgArticle",
    propOrder = {
            "brand",
            "artNo",
            "qty",
            "qu",
            "artOutline",
            "addText"
        }
)
public class TgArticle {

    //~ Instance fields --------------------------------------------------------

    @XmlElement(name = "Brand")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String brand;
    @XmlElement(name = "ArtNo")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String artNo;
    @XmlElement(name = "Qty")
    protected BigDecimal qty;
    @XmlElement(name = "QU")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String qu;
    @XmlElement(
        name = "ArtOutline",
        required = true
    )
    protected TgMLText artOutline;
    @XmlElement(name = "AddText")
    protected List<TgAddText> addText;

    //~ Methods ----------------------------------------------------------------

    /**
     * Gets the value of the brand property.
     *
     * @return  possible object is {@link String }
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     *
     * @param  value  allowed object is {@link String }
     */
    public void setBrand(final String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the artNo property.
     *
     * @return  possible object is {@link String }
     */
    public String getArtNo() {
        return artNo;
    }

    /**
     * Sets the value of the artNo property.
     *
     * @param  value  allowed object is {@link String }
     */
    public void setArtNo(final String value) {
        this.artNo = value;
    }

    /**
     * Gets the value of the qty property.
     *
     * @return  possible object is {@link BigDecimal }
     */
    public BigDecimal getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     *
     * @param  value  allowed object is {@link BigDecimal }
     */
    public void setQty(final BigDecimal value) {
        this.qty = value;
    }

    /**
     * Gets the value of the qu property.
     *
     * @return  possible object is {@link String }
     */
    public String getQU() {
        return qu;
    }

    /**
     * Sets the value of the qu property.
     *
     * @param  value  allowed object is {@link String }
     */
    public void setQU(final String value) {
        this.qu = value;
    }

    /**
     * Gets the value of the artOutline property.
     *
     * @return  possible object is {@link TgMLText }
     */
    public TgMLText getArtOutline() {
        return artOutline;
    }

    /**
     * Sets the value of the artOutline property.
     *
     * @param  value  allowed object is {@link TgMLText }
     */
    public void setArtOutline(final TgMLText value) {
        this.artOutline = value;
    }

    /**
     * Gets the value of the addText property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make
     * to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the addText property.</p>
     *
     * <p>For example, to add a new item, do as follows:</p>
     *
     * <pre>
          getAddText().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link TgAddText }</p>
     *
     * @return  DOCUMENT ME!
     */
    public List<TgAddText> getAddText() {
        if (addText == null) {
            addText = new ArrayList<TgAddText>();
        }
        return this.addText;
    }
}
