/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.23 at 11:39:14 AM CET
//
package de.cismet.cids.gaeb.xsd.types;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>Java class for tgCashDiscount complex type.</p>
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
   &lt;complexType name="tgCashDiscount">
     &lt;complexContent>
       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         &lt;sequence>
           &lt;choice>
             &lt;element name="CashDiscDays">
               &lt;complexType>
                 &lt;complexContent>
                   &lt;extension base="{http://www.gaeb.de/GAEB_DA_XML/200407}tgCashDiscDays">
                   &lt;/extension>
                 &lt;/complexContent>
               &lt;/complexType>
             &lt;/element>
             &lt;element name="CashDiscDate" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgDate"/>
           &lt;/choice>
           &lt;element name="DiscountPcnt" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgDecimal_5_2"/>
         &lt;/sequence>
       &lt;/restriction>
     &lt;/complexContent>
   &lt;/complexType>
 * </pre>
 *
 * @version  $Revision$, $Date$
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "tgCashDiscount",
    propOrder = {
            "cashDiscDays",
            "cashDiscDate",
            "discountPcnt"
        }
)
public class TgCashDiscount {

    //~ Instance fields --------------------------------------------------------

    @XmlElement(name = "CashDiscDays")
    protected TgCashDiscount.CashDiscDays cashDiscDays;
    @XmlElement(name = "CashDiscDate")
    protected XMLGregorianCalendar cashDiscDate;
    @XmlElement(
        name = "DiscountPcnt",
        required = true
    )
    protected BigDecimal discountPcnt;

    //~ Methods ----------------------------------------------------------------

    /**
     * Gets the value of the cashDiscDays property.
     *
     * @return  possible object is {@link TgCashDiscount.CashDiscDays }
     */
    public TgCashDiscount.CashDiscDays getCashDiscDays() {
        return cashDiscDays;
    }

    /**
     * Sets the value of the cashDiscDays property.
     *
     * @param  value  allowed object is {@link TgCashDiscount.CashDiscDays }
     */
    public void setCashDiscDays(final TgCashDiscount.CashDiscDays value) {
        this.cashDiscDays = value;
    }

    /**
     * Gets the value of the cashDiscDate property.
     *
     * @return  possible object is {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getCashDiscDate() {
        return cashDiscDate;
    }

    /**
     * Sets the value of the cashDiscDate property.
     *
     * @param  value  allowed object is {@link XMLGregorianCalendar }
     */
    public void setCashDiscDate(final XMLGregorianCalendar value) {
        this.cashDiscDate = value;
    }

    /**
     * Gets the value of the discountPcnt property.
     *
     * @return  possible object is {@link BigDecimal }
     */
    public BigDecimal getDiscountPcnt() {
        return discountPcnt;
    }

    /**
     * Sets the value of the discountPcnt property.
     *
     * @param  value  allowed object is {@link BigDecimal }
     */
    public void setDiscountPcnt(final BigDecimal value) {
        this.discountPcnt = value;
    }

    //~ Inner Classes ----------------------------------------------------------

    /**
     * <p>Java class for anonymous complex type.</p>
     *
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     *
     * <pre>
       &lt;complexType>
         &lt;complexContent>
           &lt;extension base="{http://www.gaeb.de/GAEB_DA_XML/200407}tgCashDiscDays">
           &lt;/extension>
         &lt;/complexContent>
       &lt;/complexType>
     * </pre>
     *
     * @version  $Revision$, $Date$
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CashDiscDays extends TgCashDiscDays {
    }
}
