/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.23 at 11:39:14 AM CET
//
package de.cismet.cids.gaeb.xsd.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for tgCOPhase.</p>
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
   &lt;simpleType name="tgCOPhase">
     &lt;restriction base="{http://www.gaeb.de/GAEB_DA_XML/200407}tgNormalizedString">
       &lt;enumeration value="CallChangOrder"/>
       &lt;enumeration value="SupplBid"/>
       &lt;enumeration value="SupplAgree"/>
     &lt;/restriction>
   &lt;/simpleType>
 * </pre>
 *
 * @version  $Revision$, $Date$
 */
@XmlType(name = "tgCOPhase")
@XmlEnum
public enum TgCOPhase {

    //~ Enum constants ---------------------------------------------------------

    @XmlEnumValue("CallChangOrder")
    CALL_CHANG_ORDER("CallChangOrder"),
    @XmlEnumValue("SupplBid")
    SUPPL_BID("SupplBid"),
    @XmlEnumValue("SupplAgree")
    SUPPL_AGREE("SupplAgree");

    //~ Instance fields --------------------------------------------------------

    private final String value;

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new TgCOPhase object.
     *
     * @param  v  DOCUMENT ME!
     */
    TgCOPhase(final String v) {
        value = v;
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public String value() {
        return value;
    }

    /**
     * DOCUMENT ME!
     *
     * @param   v  DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     *
     * @throws  IllegalArgumentException  DOCUMENT ME!
     */
    public static TgCOPhase fromValue(final String v) {
        for (final TgCOPhase c : TgCOPhase.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
}
