/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.23 at 11:39:14 AM CET
//
package de.cismet.cids.gaeb.xsd.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Informationen zur Berufsgenossenschaft.
 *
 * <p>Java class for tgInsAs complex type.</p>
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
   &lt;complexType name="tgInsAs">
     &lt;complexContent>
       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         &lt;sequence>
           &lt;element name="InsAsName" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgNormalizedString60"/>
           &lt;element name="InsAsDate" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgDate"/>
           &lt;element name="InsAsNo" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgNormalizedString20"/>
         &lt;/sequence>
       &lt;/restriction>
     &lt;/complexContent>
   &lt;/complexType>
 * </pre>
 *
 * @version  $Revision$, $Date$
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "tgInsAs",
    propOrder = {
            "insAsName",
            "insAsDate",
            "insAsNo"
        }
)
public class TgInsAs {

    //~ Instance fields --------------------------------------------------------

    @XmlElement(
        name = "InsAsName",
        required = true
    )
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String insAsName;
    @XmlElement(
        name = "InsAsDate",
        required = true
    )
    protected XMLGregorianCalendar insAsDate;
    @XmlElement(
        name = "InsAsNo",
        required = true
    )
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String insAsNo;

    //~ Methods ----------------------------------------------------------------

    /**
     * Gets the value of the insAsName property.
     *
     * @return  possible object is {@link String }
     */
    public String getInsAsName() {
        return insAsName;
    }

    /**
     * Sets the value of the insAsName property.
     *
     * @param  value  allowed object is {@link String }
     */
    public void setInsAsName(final String value) {
        this.insAsName = value;
    }

    /**
     * Gets the value of the insAsDate property.
     *
     * @return  possible object is {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getInsAsDate() {
        return insAsDate;
    }

    /**
     * Sets the value of the insAsDate property.
     *
     * @param  value  allowed object is {@link XMLGregorianCalendar }
     */
    public void setInsAsDate(final XMLGregorianCalendar value) {
        this.insAsDate = value;
    }

    /**
     * Gets the value of the insAsNo property.
     *
     * @return  possible object is {@link String }
     */
    public String getInsAsNo() {
        return insAsNo;
    }

    /**
     * Sets the value of the insAsNo property.
     *
     * @param  value  allowed object is {@link String }
     */
    public void setInsAsNo(final String value) {
        this.insAsNo = value;
    }
}
