/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.23 at 11:39:14 AM CET
//
package de.cismet.cids.gaeb.xsd.types;

import java.math.BigDecimal;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Zuordnung der Teilmengen.
 *
 * <p>Java class for tgQtySplit complex type.</p>
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
   &lt;complexType name="tgQtySplit">
     &lt;complexContent>
       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         &lt;sequence>
           &lt;choice>
             &lt;element name="QtyPcnt" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgDecimal_5_2"/>
             &lt;element name="Qty" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgDecimal_11_3"/>
           &lt;/choice>
           &lt;element name="CtlgAssign" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgCtlgAssign" maxOccurs="unbounded"/>
         &lt;/sequence>
       &lt;/restriction>
     &lt;/complexContent>
   &lt;/complexType>
 * </pre>
 *
 * @version  $Revision$, $Date$
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "tgQtySplit",
    propOrder = {
            "qtyPcnt",
            "qty",
            "ctlgAssign"
        }
)
public class TgQtySplit {

    //~ Instance fields --------------------------------------------------------

    @XmlElement(name = "QtyPcnt")
    protected BigDecimal qtyPcnt;
    @XmlElement(name = "Qty")
    protected BigDecimal qty;
    @XmlElement(
        name = "CtlgAssign",
        required = true
    )
    protected List<TgCtlgAssign> ctlgAssign;

    //~ Methods ----------------------------------------------------------------

    /**
     * Gets the value of the qtyPcnt property.
     *
     * @return  possible object is {@link BigDecimal }
     */
    public BigDecimal getQtyPcnt() {
        return qtyPcnt;
    }

    /**
     * Sets the value of the qtyPcnt property.
     *
     * @param  value  allowed object is {@link BigDecimal }
     */
    public void setQtyPcnt(final BigDecimal value) {
        this.qtyPcnt = value;
    }

    /**
     * Gets the value of the qty property.
     *
     * @return  possible object is {@link BigDecimal }
     */
    public BigDecimal getQty() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     *
     * @param  value  allowed object is {@link BigDecimal }
     */
    public void setQty(final BigDecimal value) {
        this.qty = value;
    }

    /**
     * Gets the value of the ctlgAssign property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make
     * to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the ctlgAssign property.</p>
     *
     * <p>For example, to add a new item, do as follows:</p>
     *
     * <pre>
          getCtlgAssign().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link TgCtlgAssign }</p>
     *
     * @return  DOCUMENT ME!
     */
    public List<TgCtlgAssign> getCtlgAssign() {
        if (ctlgAssign == null) {
            ctlgAssign = new ArrayList<TgCtlgAssign>();
        }
        return this.ctlgAssign;
    }
}
