/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.23 at 11:39:14 AM CET
//
package de.cismet.cids.gaeb.xsd.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Verweis auf das LV.
 *
 * <p>Java class for tgRefBoQ complex type.</p>
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
   &lt;complexType name="tgRefBoQ">
     &lt;complexContent>
       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         &lt;attribute name="IDRef" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
       &lt;/restriction>
     &lt;/complexContent>
   &lt;/complexType>
 * </pre>
 *
 * @version  $Revision$, $Date$
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tgRefBoQ")
public class TgRefBoQ {

    //~ Instance fields --------------------------------------------------------

    @XmlAttribute(
        name = "IDRef",
        required = true
    )
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object idRef;

    //~ Methods ----------------------------------------------------------------

    /**
     * Gets the value of the idRef property.
     *
     * @return  possible object is {@link Object }
     */
    public Object getIDRef() {
        return idRef;
    }

    /**
     * Sets the value of the idRef property.
     *
     * @param  value  allowed object is {@link Object }
     */
    public void setIDRef(final Object value) {
        this.idRef = value;
    }
}
