/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.23 at 11:39:14 AM CET
//
package de.cismet.cids.gaeb.xsd.types;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Textergaenzung.
 *
 * <p>Java class for tgTextComplement complex type.</p>
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>
   &lt;complexType name="tgTextComplement">
     &lt;complexContent>
       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         &lt;sequence>
           &lt;element name="ComplCaption" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgMLText"/>
           &lt;choice minOccurs="0">
             &lt;element name="ComplBodyDec" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgComplBodyDec"/>
             &lt;element name="ComplBodyInt" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgComplBodyInt"/>
           &lt;/choice>
           &lt;element name="ComplBody" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgMLText"/>
           &lt;element name="ComplTail" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgMLText"/>
         &lt;/sequence>
         &lt;attribute name="MarkLbl" use="required" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgInteger" />
         &lt;attribute name="Kind" use="required">
           &lt;simpleType>
             &lt;restriction base="{http://www.gaeb.de/GAEB_DA_XML/200407}tgNormalizedString">
               &lt;enumeration value="Bidder"/>
               &lt;enumeration value="Owner"/>
             &lt;/restriction>
           &lt;/simpleType>
         &lt;/attribute>
         &lt;attribute name="Empty" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgYes" />
         &lt;attribute name="ArtChrIdent" type="{http://www.gaeb.de/GAEB_DA_XML/200407}tgInteger" />
       &lt;/restriction>
     &lt;/complexContent>
   &lt;/complexType>
 * </pre>
 *
 * @version  $Revision$, $Date$
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "tgTextComplement",
    propOrder = {
            "complCaption",
            "complBodyDec",
            "complBodyInt",
            "complBody",
            "complTail"
        }
)
public class TgTextComplement {

    //~ Instance fields --------------------------------------------------------

    @XmlElement(
        name = "ComplCaption",
        required = true
    )
    protected TgMLText complCaption;
    @XmlElement(name = "ComplBodyDec")
    protected TgComplBodyDec complBodyDec;
    @XmlElement(name = "ComplBodyInt")
    protected TgComplBodyInt complBodyInt;
    @XmlElement(
        name = "ComplBody",
        required = true
    )
    protected TgMLText complBody;
    @XmlElement(
        name = "ComplTail",
        required = true
    )
    protected TgMLText complTail;
    @XmlAttribute(
        name = "MarkLbl",
        required = true
    )
    protected BigInteger markLbl;
    @XmlAttribute(
        name = "Kind",
        required = true
    )
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String kind;
    @XmlAttribute(name = "Empty")
    protected TgYes empty;
    @XmlAttribute(name = "ArtChrIdent")
    protected BigInteger artChrIdent;

    //~ Methods ----------------------------------------------------------------

    /**
     * Gets the value of the complCaption property.
     *
     * @return  possible object is {@link TgMLText }
     */
    public TgMLText getComplCaption() {
        return complCaption;
    }

    /**
     * Sets the value of the complCaption property.
     *
     * @param  value  allowed object is {@link TgMLText }
     */
    public void setComplCaption(final TgMLText value) {
        this.complCaption = value;
    }

    /**
     * Gets the value of the complBodyDec property.
     *
     * @return  possible object is {@link TgComplBodyDec }
     */
    public TgComplBodyDec getComplBodyDec() {
        return complBodyDec;
    }

    /**
     * Sets the value of the complBodyDec property.
     *
     * @param  value  allowed object is {@link TgComplBodyDec }
     */
    public void setComplBodyDec(final TgComplBodyDec value) {
        this.complBodyDec = value;
    }

    /**
     * Gets the value of the complBodyInt property.
     *
     * @return  possible object is {@link TgComplBodyInt }
     */
    public TgComplBodyInt getComplBodyInt() {
        return complBodyInt;
    }

    /**
     * Sets the value of the complBodyInt property.
     *
     * @param  value  allowed object is {@link TgComplBodyInt }
     */
    public void setComplBodyInt(final TgComplBodyInt value) {
        this.complBodyInt = value;
    }

    /**
     * Gets the value of the complBody property.
     *
     * @return  possible object is {@link TgMLText }
     */
    public TgMLText getComplBody() {
        return complBody;
    }

    /**
     * Sets the value of the complBody property.
     *
     * @param  value  allowed object is {@link TgMLText }
     */
    public void setComplBody(final TgMLText value) {
        this.complBody = value;
    }

    /**
     * Gets the value of the complTail property.
     *
     * @return  possible object is {@link TgMLText }
     */
    public TgMLText getComplTail() {
        return complTail;
    }

    /**
     * Sets the value of the complTail property.
     *
     * @param  value  allowed object is {@link TgMLText }
     */
    public void setComplTail(final TgMLText value) {
        this.complTail = value;
    }

    /**
     * Gets the value of the markLbl property.
     *
     * @return  possible object is {@link BigInteger }
     */
    public BigInteger getMarkLbl() {
        return markLbl;
    }

    /**
     * Sets the value of the markLbl property.
     *
     * @param  value  allowed object is {@link BigInteger }
     */
    public void setMarkLbl(final BigInteger value) {
        this.markLbl = value;
    }

    /**
     * Gets the value of the kind property.
     *
     * @return  possible object is {@link String }
     */
    public String getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     *
     * @param  value  allowed object is {@link String }
     */
    public void setKind(final String value) {
        this.kind = value;
    }

    /**
     * Gets the value of the empty property.
     *
     * @return  possible object is {@link TgYes }
     */
    public TgYes getEmpty() {
        return empty;
    }

    /**
     * Sets the value of the empty property.
     *
     * @param  value  allowed object is {@link TgYes }
     */
    public void setEmpty(final TgYes value) {
        this.empty = value;
    }

    /**
     * Gets the value of the artChrIdent property.
     *
     * @return  possible object is {@link BigInteger }
     */
    public BigInteger getArtChrIdent() {
        return artChrIdent;
    }

    /**
     * Sets the value of the artChrIdent property.
     *
     * @param  value  allowed object is {@link BigInteger }
     */
    public void setArtChrIdent(final BigInteger value) {
        this.artChrIdent = value;
    }
}
